--CREATE SCHEMA Cheap
--GO

--DROP TABLE Cheap.Customers
CREATE TABLE Cheap.Customers
(
	CustomerID INT IDENTITY NOT NULL,
	CustomerName NVARCHAR(128) NOT NULL,
	Address NVARCHAR(128) NOT NULL,
);

CREATE TABLE Cheap.Inventory
(
	Name NVARCHAR(128) NOT NULL,
	Quantity INT NOT NULL,
	Category NVARCHAR(128),
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

CREATE TABLE Cheap.CPU
(
	CPUId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Speed NVARCHAR(128) NOT NULL,
	Cores INT NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

--DROP TABLE Cheap.PowerSupply
CREATE TABLE Cheap.PowerSupply
(
	PowerSupplyId INT IDENTITY,
	Name NVARCHAR(128),
	Watage NVARCHAR(128),
	Modular NVARCHAR(128),
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

CREATE TABLE Cheap.GraphicsCard
(
	GraphicsCardId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Speed NVARCHAR(128) NOT NULL,
	Size NVARCHAR(128) NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

--DROP TABLE Cheap.HardDrive
CREATE TABLE Cheap.HardDrive
(
	HardDriveId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Speed NVARCHAR(128) NOT NULL,
	Size NVARCHAR(128) NOT NULL,
	Category NVARCHAR(128) NOT NULL,
	Price Money NOT NULL,
	Img NVARCHAR(128) NOT NULL
)

CREATE TABLE Cheap.MotherBoard
(
	MotherBoardId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	FormFactor NVARCHAR(128) NOT NULL,
	RAMSlots INT NOT NULL,
	PCISlots INT NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
)

CREATE TABLE Cheap.RAM
(
	RAMId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Speed NVARCHAR(128) NOT NULL,
	Size NVARCHAR(128) NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

CREATE TABLE Cheap.ComputerCase
(
	ComputerCaseId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Size NVARCHAR(128) NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
)

--DROP TABLE 
CREATE TABLE Cheap.PartsOrder
(
	OrderID INT IDENTITY NOT NULL,
	CustomerID INT NOT NULL,	
	FinalPrice MONEY NOT NULL,
	TimeOfOrder DATETIME NOT NULL
);

--DROP TABLE Cheap.PartsJunction
CREATE TABLE Cheap.PartsJunction
(
	Id INT IDENTITY NOT NULL,
	OrderId INT NOT NULL,
	Name NVARCHAR(128) NOT NULL
);



ALTER TABLE Cheap.Customers
ADD CONSTRAINT PK_Customers_CustomerID PRIMARY KEY (CustomerID);
GO

ALTER TABLE Cheap.Inventory
ADD CONSTRAINT PK_Inventory_Name PRIMARY KEY (Name)
GO

ALTER TABLE Cheap.CPU
ADD CONSTRAINT PK_CPU_CPUId PRIMARY KEY (CPUId)
GO

ALTER TABLE Cheap.PowerSupply
ADD CONSTRAINT PK_PowerSupply_PowerSupplyId PRIMARY KEY (PowerSupplyId)
GO

ALTER TABLE Cheap.GraphicsCard
ADD CONSTRAINT PK_GraphicsCard_GraphicsCardId PRIMARY KEY (GraphicsCardId)
GO

ALTER TABLE Cheap.HardDrive
ADD CONSTRAINT PK_HardDrive_HardDriveId PRIMARY KEY (HardDriveId)
GO

ALTER TABLE Cheap.MotherBoard
ADD CONSTRAINT PK_MotherBoard_MotherBoardId PRIMARY KEY (MotherBoardId)
GO

ALTER TABLE Cheap.RAM
ADD CONSTRAINT PK_RAM_RAMId PRIMARY KEY (RAMId)
GO

ALTER TABLE Cheap.ComputerCase
ADD CONSTRAINT PK_ComputerCase_ComputerCaseId PRIMARY KEY (ComputerCaseId)
GO

ALTER TABLE Cheap.PartsOrder
ADD CONSTRAINT PK_PartsOrder_OrderID PRIMARY KEY (OrderID)
GO

ALTER TABLE Cheap.PartsJunction
ADD CONSTRAINT PK_PartsJunction_Id PRIMARY KEY (Id)
GO






ALTER TABLE Cheap.PartsOrder
ADD CONSTRAINT FK_PartsOrder_CustomerID FOREIGN KEY(CustomerID) REFERENCES Cheap.Customers(CustomerID)
GO

ALTER TABLE Cheap.PartsJunction
ADD CONSTRAINT FK_PartsJunction_OrderID FOREIGN KEY(OrderId) REFERENCES Cheap.PartsOrder(OrderID)

ALTER TABLE Cheap.PartsJunction
ADD CONSTRAINT FK_PartsJunction_Name FOREIGN KEY(Name) REFERENCES Cheap.Inventory(Name)

ALTER TABLE Cheap.CPU
ADD CONSTRAINT FK_CPU_Name FOREIGN KEY (Name) REFERENCES Cheap.Inventory(Name)
GO

ALTER TABLE Cheap.PowerSupply
ADD CONSTRAINT FK_PowerSupply_Name FOREIGN KEY (Name) REFERENCES Cheap.Inventory(Name)
GO

ALTER TABLE Cheap.GraphicsCard
ADD CONSTRAINT FK_GraphicsCard_Name FOREIGN KEY (Name) REFERENCES Cheap.Inventory(Name)
GO

ALTER TABLE Cheap.HardDrive
ADD CONSTRAINT FK_HardDrive_Name FOREIGN KEY (Name) REFERENCES Cheap.Inventory(Name)
GO

ALTER TABLE Cheap.MotherBoard
ADD CONSTRAINT FK_MotherBoard_Name FOREIGN KEY (Name) REFERENCES Cheap.Inventory(Name)
GO

ALTER TABLE Cheap.RAM
ADD CONSTRAINT FK_RAM_Name FOREIGN KEY (Name) REFERENCES Cheap.Inventory(Name)
GO

ALTER TABLE Cheap.ComputerCase
ADD CONSTRAINT FK_ComputerCase_Name FOREIGN KEY (Name) REFERENCES Cheap.Inventory(Name)
GO




SELECT * FROM Cheap.Customers

SELECT * FROM Cheap.CPU

SELECT * FROM Cheap.RAM

SELECT * FROM Cheap.PowerSupply

SELECT * FROM Cheap.MotherBoard

SELECT * FROM Cheap.ComputerCase

SELECT * FROM Cheap.HardDrive

SELECT * FROM Cheap.GraphicsCard

SELECT * FROM Cheap.PartsOrder

SELECT * FROM Cheap.PartsJunction


