--CREATE SCHEMA Cheap
--GO

--DROP TABLE Cheap.Customers
CREATE TABLE Cheap.Customers
(
	CustomerID INT IDENTITY NOT NULL,
	CustomerName NVARCHAR(128) NOT NULL,
	Address NVARCHAR(128) NOT NULL,
);

--DROP TABLE Cheap.Locations
CREATE TABLE Cheap.Locations
(
	StoreNumber INT IDENTITY NOT NULL,
	
);

CREATE TABLE Cheap.Inventory
(
	Name NVARCHAR(128) NOT NULL,
	Quantity INT NOT NULL,
	Category NVARCHAR(128),
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

CREATE TABLE Cheap.CPU
(
	CPUId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Speed NVARCHAR(128) NOT NULL,
	Cores INT NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

CREATE TABLE Cheap.PowerSupply
(
	PowerSupply INT IDENTITY,
	Name NVARCHAR(128),
	Watage NVARCHAR(128),
	Modular NVARCHAR(128),
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

CREATE TABLE Cheap.GraphicsCard
(
	GraphicsCardId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Speed NVARCHAR(128) NOT NULL,
	Size NVARCHAR(128) NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

CREATE TABLE Cheap.HardDrive
(
	HardDriveId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Speed NVARCHAR(128) NOT NULL,
	Size NVARCHAR(128) NOT NULL,
	Category NVARCHAR(128) NOT NULL,
	Img NVARCHAR(128) NOT NULL
)

CREATE TABLE Cheap.MotherBoard
(
	MotherBoardId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	FormFactor NVARCHAR(128) NOT NULL,
	RAMSlots INT NOT NULL,
	PCISlots INT NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
)

CREATE TABLE Cheap.RAM
(
	RAMId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Speed NVARCHAR(128) NOT NULL,
	Size NVARCHAR(128) NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
);

CREATE TABLE Cheap.ComputerCase
(
	ComputerCaseId INT IDENTITY NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Size NVARCHAR(128) NOT NULL,
	Price MONEY NOT NULL,
	Img NVARCHAR(128) NOT NULL
)



--DROP TABLE PizzaStore.Orders
CREATE TABLE Cheap.PartsOrder
(
	OrderID INT IDENTITY NOT NULL,
	CustomerID INT NOT NULL,	
	FinalPrice MONEY NOT NULL,
	TimeOfOrder DATETIME NOT NULL
);

CREATE TABLE Cheap.PartsJunction
(
	Id INT IDENTITY NOT NULL,
	OrderId INT NOT NULL,
	Name VARCHAR(128) NOT NULL
);



ALTER TABLE PizzaStore.Inventory
ADD CONSTRAINT FK_Inventory_InventoryID FOREIGN KEY (InventoryID) REFERENCES PizzaStore.Locations(StoreNumber)
GO


ALTER TABLE PizzaStore.Orders
ADD CONSTRAINT FK_Order_StoreNumber FOREIGN KEY (StoreNumber) REFERENCES PizzaStore.Locations(StoreNumber)
GO

ALTER TABLE PizzaStore.Orders
ADD CONSTRAINT FK_Orders_UserID FOREIGN KEY (UserID) REFERENCES PizzaStore.Users(ID)
GO

ALTER TABLE PizzaStore.PizzaPie
ADD CONSTRAINT FK_PizzaPie_OrderID FOREIGN KEY (OrderID) REFERENCES PizzaStore.Orders(OrderID)
GO


ALTER TABLE PizzaStore.Users
ADD CONSTRAINT FK_Users_PrefLocation FOREIGN KEY (PrefLocation) REFERENCES PizzaStore.Locations(StoreNumber)
GO

ALTER TABLE PizzaStore.Users
ADD CONSTRAINT PK_Users_ID PRIMARY KEY (ID);
GO

ALTER TABLE PizzaStore.Orders
ADD CONSTRAINT PK_Orders_OrderID PRIMARY KEY (OrderID)
GO

ALTER TABLE PizzaStore.PizzaPie
ADD CONSTRAINT PK_PizzaPie_ID PRIMARY KEY (ID)
GO

ALTER TABLE PizzaStore.Locations
ADD CONSTRAINT PK_Locations_StoreNumber PRIMARY KEY (StoreNumber)
GO

