FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Cheapware.API/*.csproj ./Cheapware.API/
COPY Cheapware.Data/*.csproj ./Cheapware.Data/
COPY Cheapware.Library/*.csproj ./Cheapware.Library/
COPY Cheapware.Service.Test/*.csproj ./Cheapware.Service.Test/

RUN dotnet restore

# copy everything else and build app
COPY . ./
WORKDIR /app/Cheapware.API
RUN dotnet publish -c Release -o out


FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/Cheapware.API/out ./
ENTRYPOINT ["dotnet", "CheapWare.API.dll"]
